templateDir: ./mustache_templates
files:
  electron-sdk-wrapper.mustache:
    templateType: SupportingFiles
    destinationFilename: app/sailpoint-sdk/sailpoint-sdk.ts
  electron-icp-handlers.mustache:
    templateType: SupportingFiles
    destinationFilename: app/sailpoint-sdk/ipc-handlers.ts
  electron-preload.mustache:
    templateType: SupportingFiles
    destinationFilename: app/sailpoint-sdk/sdk-preload.ts
  sailpoint-sdk-service.mustache:
    templateType: SupportingFiles
    destinationFilename: /projects/sailpoint-components/src/lib/sailpoint-sdk.service.ts
npmName: sailpoint-sdk
npmRepository: sailpoint.com
npmVersion: 1.6.0
useSingleRequestParameter: true
apiVersion: v2025
enumNameSuffix: V2025