# This is a basic workflow to help you get started with Actions
name: 'Windows Build'

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
permissions:
  contents: read

jobs:
  build:

    # The type of runner that the job will run on
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        cache: 'yarn'

    - name: Install Dependencies
      run: |
        yarn install

    - name: Install Angular CLI Globally
      run: yarn install -g @angular/cli

    - name: Check lint
      run: yarn lint

    - name: Build Component Library
      run: yarn build:components

    - name: Run headless unit test
      run: yarn test

    - name: Run headless e2e test
      run: |
       yarn e2e

    - name: Build the app
      run: yarn electron:build

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: built-electron-app
        path: release\sailpoint-ui-development-kit 1.0.0.exe